workflows:
  flutter-ci-cd:
    name: Flutter CI/CD
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter test
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
publishing:
  email:
    recipients:
      - eng.abdullahahmed59@gmail.com
    notify:
      success: true
