workflows:
  flutter-ci-cd:
    name: Flutter CI/CD
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter test
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

publishing:
  firebase:
    firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    android:
      app_id: 1:1022031179507:android:18899cdd16527fc2d6d186
      groups:
        - testers
    notify:
      success: true
      failure: true
